### ISSUE TITLE
 O_DIRECTフラグなしでFileNVMを生成可能にする

### ISSUE THREAD

**Issue by sile** [frugalos/cannyls#1]
https://github.o-in.dwango.co.jp/frugalfs/cannyls/blob/master/src/nvm/file.rs に以下のような`FileNvmBuilder`構造体を追加して、ダイレクトI/Oを使用しないモードを選択可能にする。

```rust
struct FileNvmBuilder { ... }
impl FileNvmBuilder {
    pub fn direct_io(&mut self, enabled: bool) -> &mut Self { ... }
    pub fn finish(&self, ...) -> Result<FileNvm> { ... }
}

**Comment by yuezato** [comment]
PR4で対応済み: https://github.com/frugalos/cannyls/pull/4
